# Generated by Django 4.1.3 on 2023-08-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resim",
            name="resim",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
